// Generated by CoffeeScript 1.6.3
(function() {
  Storage.prototype.setObject = function(key, val) {
    return this.setItem(key, JSON.stringify(val));
  };

  Storage.prototype.getObject = function(key) {
    var val;
    val = this.getItem(key);
    return val && JSON.parse(val);
  };

  Storage.prototype.pushObject = function(key, val) {
    var a;
    a = this.getObject(key) || [];
    a.push(val);
    return this.setObject(key, a);
  };

  navigator.geolocation.getCurrentPosition(function(position) {
    var add_marker, friends, map, me;
    me = {
      lat: position.coords.latitude,
      lng: position.coords.longitude
    };
    add_marker = function(friend) {
      return map.addMarker({
        lat: friend.lat,
        lng: friend.lng,
        title: friend.name,
        infoWindow: {
          content: "<div class='info'>\n  <h1><a href='tel:" + friend.phone + "'>" + friend.name + "</a> <small>" + friend.phone + "</small></h1>\n  <h3>" + friend.address + "</h3>\n</div>"
        }
      });
    };
    map = new GMaps({
      div: '#map-canvas',
      zoom: 12,
      lat: me.lat,
      lng: me.lng
    });
    map.addMarker(me);
    friends = localStorage.getObject('map-my-friends') || [];
    friends.forEach(add_marker);
    return document.getElementById('save').addEventListener('click', function() {
      var address, name, phone, _ref;
      _ref = ['name', 'phone', 'address'].map(function(a) {
        return document.getElementById(a);
      }), name = _ref[0], phone = _ref[1], address = _ref[2];
      return GMaps.geocode({
        address: address.value,
        callback: function(results, status) {
          var friend, latlng;
          if (status === 'OK') {
            latlng = results[0].geometry.location;
            friend = {
              lat: latlng.lat(),
              lng: latlng.lng(),
              name: name.value,
              phone: phone.value,
              address: address.value
            };
            [name, phone, address].forEach(function(i) {
              return i.value = '';
            });
            map.setCenter(friend.lat, friend.lng);
            add_marker(friend);
            return localStorage.pushObject('map-my-friends', friend);
          }
        }
      });
    });
  });

}).call(this);
